baseURL: "https://kh-rahbi.netlify.app//"
languageCode: en-us
title:  Khalid Rahbi #Abdur Rahman
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    #- identifier: blog
     # name: Blog
      #url: /blog
      #weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    #- identifier: search
    #  name: Search
    #  url: /search
    #  weight: 50
   # - identifier: tags
    #   name: Tags
     #  url: /tags
      # weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Khalid Rahbi"
    subtitle: "**Results-oriented** **Electrical Engineer** with a proven track record in **data analysis**, **research**, and **problem-solving**. Skilled in conducting thorough tests, optimizing performance, and driving user adoption of digital applications. Proficient in a wide range of programs and languages, including **Amazon Web Services**, **Google Cloud**, **Big Query**, **Python**, **HTML/CSS**, **Jira**, **Agile Scrum**, and **Confluence**, to deliver **data-driven solutions**. Passionate about the convergence of **Digital Marketing** and **artificial intelligence**, as well as **Data Engineering**. Demonstrates the ability to analyze intricate information and provide practical recommendations for effective action. Recognized for exceptional collaboration and communication skills, fostering a cohesive team environment. Committed to continuous learning and keeping up with the latest advancements in technology. Open to global relocation, eager to embrace new opportunities"
    imageUrl: "home/me.jpg"
    imageWidth: 200
    imageHeight: 300

    buttons:
    - name: Resume
      url: "https://drive.google.com/file/d/1wMMmPvLK_F7kYtwrEbdLoyWsDE5WBO3m/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:kh.rahbi@outlook.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/khaled-alrahbi/"
    - name: "github"
      url: "https://github.com/alrah003"
    - name: "youtube"
      url: "https://www.youtube.com/c/AbdurRahmanKalim"
    - name: "cv"
      url: "https://drive.google.com/file/d/1MITtIbPfxvi1NJ0Cvl3mUWGh8Enno5J8/view?usp=sharing"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
